# Generated by Django 4.2.11 on 2024-04-15 05:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('description', models.TextField()),
                ('reviews', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inventory_management_system_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('last_stocked_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inventory_management_system_app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_inventory_management_system_app.store')),
            ],
        ),
    ]
