# Generated by Django 4.2.11 on 2024-04-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
    ]
