# Generated by Django 4.2.11 on 2024-04-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory_management_system_app', '0006_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
