# Generated by Django 4.2.11 on 2024-04-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory_management_system_app', '0008_alter_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
